version: '3.9'
services:
   web:
       build: .
       command: python3 manage.py runserver localhost:8000
       ports:
           - 8000:8000
       depends_on:
         - db
         - redis
         - celery


   db:
       restart: always
       image: postgres:latest
       container_name: db_postgres
       volumes:
         - ./data/postgres:/var/lib/postgresql/data
       env_file:
         - configs/db.env
       ports:
         - "5432:5432"


   redis:
       image: "redis:alpine"

       command: redis-server --requirepass 20100327

       ports:
         - "6379:6379"

       volumes:
         - ./data/redis/redis-data:/var/lib/redis
         - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf

       environment:
         - REDIS_REPLICATION_MODE=master


   celery:
       build: .
       container_name: celery
       environment:
         - CELERY_BROKER_URL=redis
       command:
         - celery -A onlineautoshop worker -l info
       depends_on:
         - redis

     